const products=[
 {id:1,name:'حقيبة ظهر Menzio',price:4000,desc:'حقيبة ظهر عملية وأنيقة للاستخدام اليومي',image:'assets/product-1.jpg'},
 {id:2,name:'منتج تجريبي 2',price:1600,desc:'سيتم استبدال هذا المنتج ببياناتك الحقيقية',symbol:'2'},
 {id:3,name:'منتج تجريبي 3',price:2400,desc:'سيتم استبدال هذا المنتج ببياناتك الحقيقية',symbol:'3'}
];
const wilayas=['أدرار','الشلف','الأغواط','أم البواقي','باتنة','بجاية','بسكرة','بشار','البليدة','البويرة','تمنراست','تبسة','تلمسان','تيارت','تيزي وزو','الجزائر','الجلفة','جيجل','سطيف','سعيدة','سكيكدة','سيدي بلعباس','عنابة','قالمة','قسنطينة','المدية','مستغانم','المسيلة','معسكر','ورقلة','وهران','البيض','إليزي','برج بوعريريج','بومرداس','الطارف','تندوف','تيسمسيلت','الوادي','خنشلة','سوق أهراس','تيبازة','ميلة','عين الدفلى','النعامة','عين تموشنت','غرداية','غليزان','تيميمون','برج باجي مختار','أولاد جلال','بني عباس','إن صالح','إن قزام','تقرت','جانت','المغير','المنيعة'];
const WHATSAPP='213792740889';
let cart=[];
let orderSubmitting=false;
const money=n=>new Intl.NumberFormat('fr-DZ').format(n)+' دج';
function renderProducts(){document.getElementById('productGrid').innerHTML=products.map(p=>`<article class="product"><div class="product-image">${p.image?`<img src="${p.image}" alt="${p.name}">`:(p.symbol||'M')}</div><div class="product-body"><h3>${p.name}</h3><p>${p.desc}</p><div class="product-row"><span class="price">${money(p.price)}</span><button class="add" onclick="addToCart(${p.id})">أضف للسلة</button></div></div></article>`).join('')}
function addToCart(id){const product=products.find(x=>x.id===id);if(!product)return;const item=cart.find(x=>x.id===id);if(item)item.qty++;else cart.push({...product,qty:1});renderCart();openCart()}
function removeFromCart(id){cart=cart.filter(x=>x.id!==id);renderCart()}
function getCartQuantity(){return cart.reduce((s,x)=>s+x.qty,0)}
function getCartTotal(){return cart.reduce((s,x)=>s+x.price*x.qty,0)}
function renderCart(){const count=getCartQuantity(),total=getCartTotal();document.getElementById('cartCount').textContent=count;document.getElementById('cartTotal').textContent=money(total);const box=document.getElementById('cartItems');box.innerHTML=cart.length?cart.map(x=>`<div class="cart-item"><div><h4>${x.name}</h4><small>${x.qty} × ${money(x.price)}</small></div><button class="remove" onclick="removeFromCart(${x.id})">حذف</button></div>`).join(''):'<p class="empty">السلة فارغة حاليًا.</p>'}
function openCart(){document.getElementById('cartPanel').classList.add('open');document.getElementById('cartPanel').setAttribute('aria-hidden','false');document.getElementById('overlay').classList.add('show')}
function closeCart(){document.getElementById('cartPanel').classList.remove('open');document.getElementById('cartPanel').setAttribute('aria-hidden','true');document.getElementById('overlay').classList.remove('show')}
function fillWilayas(){const select=document.getElementById('wilaya');select.insertAdjacentHTML('beforeend',wilayas.map(w=>`<option value="${w}">${w}</option>`).join(''))}
function openOrderForm(){if(!cart.length){alert('أضف منتجًا إلى السلة أولًا.');return}document.getElementById('orderForm').hidden=false;document.getElementById('checkoutButton').hidden=true;document.getElementById('quantity').value=getCartQuantity()}
function buildWhatsAppMessage(data){const items=cart.map(x=>`• ${x.name} — ${x.qty} × ${money(x.price)}`).join('\n');return `طلب جديد من متجر MENZIO 🛍️\n\nرقم الطلب: ${data.ref}\nالمنتجات:\n${items}\n\nالاسم: ${data.name}\nالهاتف: ${data.phone}\nالولاية: ${data.wilaya}\nالعنوان: ${data.address}\nالمقاس: ${data.size}\nالكمية: ${data.quantity}\nالمجموع: ${money(data.total)}\n\nطريقة الدفع: الدفع عند الاستلام 💵\nشركة التوصيل: كازي تور 🚚`}
document.getElementById('cartButton').onclick=openCart;document.getElementById('closeCart').onclick=closeCart;document.getElementById('overlay').onclick=closeCart;document.getElementById('checkoutButton').onclick=openOrderForm;
document.getElementById('orderForm').addEventListener('submit',e=>{e.preventDefault();if(orderSubmitting||!cart.length)return;const form=e.currentTarget;if(!form.reportValidity())return;const name=document.getElementById('customerName').value.trim();const phone=document.getElementById('customerPhone').value.trim();const wilaya=document.getElementById('wilaya').value;const address=document.getElementById('address').value.trim();const size=document.getElementById('size').value;const quantity=getCartQuantity();const total=getCartTotal();if(quantity<1||quantity>20){alert('الكمية الإجمالية يجب أن تكون بين 1 و20.');return}orderSubmitting=true;document.getElementById('submitOrder').disabled=true;const ref='MZ-'+Date.now().toString().slice(-7);const message=buildWhatsAppMessage({ref,name,phone,wilaya,address,size,quantity,total});document.getElementById('orderSuccess').hidden=false;document.getElementById('orderSuccess').innerHTML=`<strong>تم تجهيز الطلب ✅</strong><br>رقم الطلب: <b>${ref}</b><br><small>سيتم فتح WhatsApp لإرسال تفاصيل الطلب.</small>`;window.open(`https://wa.me/${WHATSAPP}?text=${encodeURIComponent(message)}`,'_blank','noopener,noreferrer');});
fillWilayas();renderProducts();renderCart();
